# Generated by Django 4.2.1 on 2026-05-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='attachment',
            field=models.FileField(null=True, upload_to='email_attachments/%Y/%m/%d', verbose_name='Attachment'),
        ),
    ]
