version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9-node
      - image: circleci/postgres:12.3
        environment:
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
          POSTGRES_DB: mailing

    working_directory: ~/mailing

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run flake8
          command: |
            . venv/bin/activate
            flake8 --config=./tox.ini

      # run tests!
      - run: echo 'export PYTHONPATH=$PWD:$PYTHONPATH' >> $BASH_ENV
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            py.test tests/
          environment:
            DATABASE_URL: postgres://dev:dev@localhost:5432/mailing
            DJANGO_SETTINGS_MODULE: tests.test_settings
            ALLOWED_HOSTS: "*"
            PYTHONPATH: ./
